name: Stop Minecraft Server

on:
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: |
          az vm deallocate \
            --resource-group mcserv \
            --name Minecraft-Server